import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

export default function TermsOfServiceScreen() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Terms of Service</Text>
      <Text style={styles.updated}>Last updated: April 2025</Text>

      <Section title="1. Acceptance of Terms">
        By accessing and using CrossChecker, you accept and agree to be bound by these Terms of Service.
      </Section>

      <Section title="2. Use of Service">
        You agree to use the service only for lawful purposes and in a way that does not infringe the rights of others or restrict their use of the service.
      </Section>

      <Section title="3. User Account">
        You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
      </Section>

      <Section title="4. CV Generation">
        The CVs generated by our service are based on the information you provide. You are responsible for the accuracy of the information submitted.
      </Section>

      <Section title="5. Intellectual Property">
        The service and its original content, features, and functionality are owned by CrossChecker and are protected by applicable intellectual property laws.
      </Section>

      <Section title="6. Termination">
        We may terminate or suspend your account at any time without prior notice if you breach these Terms of Service.
      </Section>

      <Section title="7. Limitation of Liability">
        CrossChecker shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the service.
      </Section>

      <Section title="8. Contact Us">
        If you have any questions about these Terms, please contact us at FontysOulu@crosschecker.io
      </Section>
    </ScrollView>
  );
}

const Section = ({ title, children }: { title: string; children: string }) => (
  <View style={styles.section}>
    <Text style={styles.sectionTitle}>{title}</Text>
    <Text style={styles.sectionBody}>{children}</Text>
  </View>
);

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fb' },
  content: { padding: 20, paddingBottom: 48 },
  title: { fontSize: 24, fontWeight: '700', color: '#24313c', marginBottom: 4 },
  updated: { fontSize: 12, color: '#90a4ae', marginBottom: 24 },
  section: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: '#3d6fd8', marginBottom: 8 },
  sectionBody: { fontSize: 14, color: '#556070', lineHeight: 22 },
});